### ISSUE TITLE
Can anyone, please recompile the Bytecode for ESP8266 

### ISSUE THREAD

**Issue by ThomasAtBaum** [chrisb2/pyb_ina219#2]
It seems to me that the bytecode for ESP8266 only works for Micropython version 1.9.1 
Can anyone please recompile for version 1.9.3 and/or 1.94?
Thanks

**Comment by chrisb2** [comment]
Try the attached which where built for 1.9.4. I have not had chance to test them as my time is pretty limited in the next few days.

[esp8266.zip](https://github.com/chrisb2/pyb_ina219/files/2734184/esp8266.zip)

**Comment by captain-sysadmin** [comment]
Using mpy-cross is a quick and painless way to compile bytecode. You need to make sure you pip install the correct version for your micropython version though.

**Comment by tuxillo** [comment]
I've just built it myself for 1.11 but maybe some people find it helpful if there is a download link for the latest micropython versions, time is scarce!

**Comment by captain-sysadmin** [comment]
`mpy_cross ina219.py -march=xtensa `

should output ina219.mpy. copy that over to the ESP and it should work like a charm. This has the advantage that they can do it for any version they please.
