### ISSUE TITLE
Shunt resistor value

### ISSUE THREAD

**Issue by csebe12** [chrisb2/pyb_ina219#4]
Hi,

I'm using this library with the Gravity I2C digital wattmeter which uses the INA219 sensor. According to the schematic the value of the shunt resistor is 0.01 Ohm not 0.1 Ohm. Could you please look into this and correct your example if necessary?

Thanks,
Ben

**Comment by chrisb2** [comment]
The more common Adafruit [ina219](https://www.adafruit.com/product/904) board has a 0.1 Ohm resistor, I am guessing on that gravity board they wanted to measure smaller currents and so reduce the shunt to 0.01 Ohm. Given the popularity of adafruit sensor I am going to leave the value at 0.1 Ohm, but I will update the example to warn people to check their board.

regards,
Chris
