### ISSUE TITLE
ValueError: incompatible .mpy file

### ISSUE THREAD

**Issue by fanlessfan** [chrisb2/pyb_ina219#5]
I got error when I try to import ina219.mpy in a ESP8266 broad. (D1 mini)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: incompatible .mpy file

**Comment by chrisb2** [comment]
Sorry I should have deleted the .mpy files a long time ago, they are not portable between versions of micropython and I would have to build and maintain a load of versions. You can build them yourself as explained in:
[https://github.com/micropython/micropython/tree/master/mpy-cross](https://github.com/micropython/micropython/tree/master/mpy-cross)

Quickest way to get going is probably docker image mentioned in:
[https://github.com/micropython/micropython/tree/master/ports/esp8266](https://github.com/micropython/micropython/tree/master/ports/esp8266)

Chris
