### ISSUE TITLE
No module named logging

### ISSUE THREAD

**Issue by mrnotfalco** [chrisb2/pyb_ina219#6]
When I try to use the INA219 library with micropython, using a Raspberry Pi Pico, I get the "ImportError: no module named 'logging'" error. I can't seem to find the logging library anywhere so I can't manually add it. Any suggestions?

**Comment by chrisb2** [comment]
logging.py is linked in the readme, but they were broken, I have fixed them. This is the link: [logging.py](https://raw.githubusercontent.com/micropython/micropython-lib/master/python-stdlib/logging/logging.py)

Chris

**Comment by mrnotfalco** [comment]
This seems to have fixed the problem, thanks!
